# Generated by Django 4.2 on 2024-05-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userfullnameemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfullnameemail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userfullnameemail',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userfullnameemail',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
