# Generated by Django 4.2 on 2024-05-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userfullnameemail_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfullnameemail',
            old_name='user',
            new_name='owner',
        ),
    ]
