# Generated by Django 4.2 on 2024-05-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_user_userfullnameemail_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfullnameemail',
            options={'verbose_name_plural': 'Profile persona'},
        ),
    ]
