# Generated by Django 4.2 on 2024-05-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile2',
        ),
    ]
