# Generated by Django 4.2 on 2024-05-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Shipped'), (2, 'Delivered'), (3, 'Delivery Failed'), (4, 'Canceled')], default=0),
        ),
    ]
