# Generated by Django 4.2 on 2024-05-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderlineitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Delivery Failed'), (5, 'Cancelled')], default=0),
        ),
    ]
