# Generated by Django 4.2 on 2024-05-14 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_shipping'),
        ('checkout', '0005_alter_orderlineitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_shipping_fee', to='products.product'),
        ),
    ]
