# Generated by Django 4.2 on 2024-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_orderlineitem_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Mr', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
