# Generated by Django 4.2 on 2024-05-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorregistration',
            name='current_website',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='vendorregistration',
            name='store_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
