# Generated by Django 4.2 on 2024-05-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_coupon_valid_from_alter_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name_plural': 'Coupon Codes'},
        ),
    ]
