# Generated by Django 4.2 on 2024-04-27 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.IntegerField(choices=[(0, 'draft'), (1, 'published')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('description', models.TextField()),
                ('has_sizes', models.BooleanField(blank=True, default=False, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, help_text='Enter tags separated by commas', max_length=254, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Weight of the product in kilograms', max_digits=10)),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'draft'), (1, 'published')], default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('vendor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
