# Generated by Django 4.2 on 2024-05-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_cost_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Shipping fee for this product', max_digits=6, null=True),
        ),
    ]
